global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'flink'
    static_configs:
#      - targets: ['app-cluster:9249']   # matches the service + port above
      - targets: ['host.docker.internal:9249']
